language: node_js
node_js:
  - "stable"
# Build Doc site
cache:
  yarn: true

# Overall builds only on branches not master
# if: branch != master
# script:
#     - git config --global user.name "${GH_NAME}"
#     - git config --global user.email "${GH_EMAIL}"
#     - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
#     - cd ./docs && npm install && GIT_USER="${GH_NAME}" docusaurus deploy

# Overall builds only on master
if: branch = master
# script:
#     - git config --global user.name "${GH_NAME}"
#     - git config --global user.email "${GH_EMAIL}"
#     - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
#     - cd ./docs && npm install && GIT_USER="${GH_NAME}" docusaurus deploy